name: Dagger CI Pipeline

on:
  push:
    branches: [ main, dev, dagger ]
  pull_request:
    branches: [ main, dev ]

jobs:
  dagger-ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dagger
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dagger.txt

    - name: Test Dagger installation
      run: python test_dagger.py

    - name: Run Dagger CI Pipeline
      run: python dagger_pipeline.py
      env:
        # Ensure we have the necessary environment variables
        PYTHONPATH: ${{ github.workspace }}

    - name: Upload coverage reports (if available)
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-report
        path: htmlcov/
        retention-days: 30
